// ============================================
// TASKLYN — List appearance presets (single source of truth)
// Used by CreateListModal and EditListModal.
// ============================================

import type { LucideIcon } from "lucide-react";
import {
  Users,
  Home,
  Briefcase,
  ShoppingCart,
  GraduationCap,
  Heart,
  Plane,
  Landmark,
  Gamepad2,
  Calendar,
  Lightbulb,
  MoreHorizontal,
  Dumbbell,
  UtensilsCrossed,
  Cpu,
} from "lucide-react";

export interface ListColorOption {
  value: string;
  label: string;
}

export interface EmojiCategory {
  id: string;
  name: string;
  icon: LucideIcon;
  emojis: string[];
}

export const LIST_COLORS: ListColorOption[] = [
  { value: "#2563eb", label: "Azul" },
  { value: "#4f46e5", label: "Índigo" },
  { value: "#7c3aed", label: "Violeta" },
  { value: "#9333ea", label: "Púrpura" },
  { value: "#db2777", label: "Rosa" },
  { value: "#e11d48", label: "Rojo" },
  { value: "#ea580c", label: "Naranja" },
  { value: "#d97706", label: "Ámbar" },
  { value: "#ca8a04", label: "Amarillo" },
  { value: "#65a30d", label: "Lima" },
  { value: "#16a34a", label: "Verde" },
  { value: "#059669", label: "Esmeralda" },
  { value: "#0d9488", label: "Teal" },
  { value: "#0891b2", label: "Cian" },
  { value: "#475569", label: "Pizarra" },
  { value: "#1e293b", label: "Carbon" },
];

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: "work",
    name: "Trabajo",
    icon: Briefcase,
    emojis: [
      "💼",
      "📁",
      "📊",
      "🖥️",
      "📅",
      "📎",
      "📌",
      "✏️",
      "📋",
      "📝",
      "🤝",
      "🗂️",
    ],
  },
  {
    id: "home",
    name: "Casa",
    icon: Home,
    emojis: [
      "🏠",
      "🧹",
      "🛋️",
      "🪴",
      "🛏️",
      "🍳",
      "🧺",
      "🚪",
      "💡",
      "🧯",
      "🛁",
      "🔑",
    ],
  },
  {
    id: "shopping",
    name: "Compras",
    icon: ShoppingCart,
    emojis: [
      "🛒",
      "🛍️",
      "🍎",
      "🥦",
      "🥛",
      "🍞",
      "🧴",
      "🧻",
      "🎁",
      "💳",
      "🥩",
      "🍷",
    ],
  },
  {
    id: "school",
    name: "Escuela",
    icon: GraduationCap,
    emojis: [
      "📚",
      "✏️",
      "📓",
      "📝",
      "🖍️",
      "🎒",
      "📐",
      "🔬",
      "🌍",
      "📖",
      "🧮",
      "🎨",
    ],
  },
  {
    id: "health",
    name: "Salud / Bienestar",
    icon: Heart,
    emojis: [
      "❤️",
      "💊",
      "🩺",
      "🏥",
      "🧘",
      "🥗",
      "💪",
      "🩹",
      "🧴",
      "🌡️",
      "🏃",
      "🍵",
    ],
  },
  {
    id: "travel",
    name: "Viajes",
    icon: Plane,
    emojis: [
      "✈️",
      "🚗",
      "🌎",
      "🏖️",
      "🗺️",
      "🧳",
      "🚢",
      "🚂",
      "🏕️",
      "📸",
      "🛂",
      "🧭",
    ],
  },
  {
    id: "finance",
    name: "Finanzas",
    icon: Landmark,
    emojis: [
      "💰",
      "💳",
      "📈",
      "📉",
      "🏦",
      "🪙",
      "💵",
      "📊",
      "🧾",
      "🔒",
      "💎",
      "🏛️",
    ],
  },
  {
    id: "sports",
    name: "Deportes",
    icon: Dumbbell,
    emojis: [
      "⚽",
      "🏀",
      "🏈",
      "⚾",
      "🎾",
      "🏐",
      "🏉",
      "🎱",
      "🏓",
      "🏸",
      "🥊",
      "🏋️",
    ],
  },
  {
    id: "food",
    name: "Comida",
    icon: UtensilsCrossed,
    emojis: [
      "🍔",
      "🍕",
      "🍣",
      "🥗",
      "🍰",
      "☕",
      "🍷",
      "🍹",
      "🍪",
      "🥑",
      "🍇",
      "🥘",
    ],
  },
  {
    id: "people",
    name: "Personas",
    icon: Users,
    emojis: [
      "👤",
      "👥",
      "🙋",
      "💁",
      "🧑‍💻",
      "👨‍👩‍👧",
      "🤝",
      "❤️",
      "🎭",
      "👶",
      "🧓",
      "👩‍🏫",
    ],
  },
  {
    id: "projects",
    name: "Proyectos",
    icon: Lightbulb,
    emojis: [
      "🚀",
      "🎯",
      "💡",
      "⭐",
      "🔥",
      "🏆",
      "📈",
      "🧩",
      "⚙️",
      "🔧",
      "🛠️",
      "📦",
    ],
  },
  {
    id: "tech",
    name: "Tecnología",
    icon: Cpu,
    emojis: [
      "💻",
      "📱",
      "⌨️",
      "🖱️",
      "🌐",
      "🤖",
      "⚡",
      "🔋",
      "📡",
      "🛜",
      "🔌",
      "🧠",
    ],
  },
  {
    id: "organization",
    name: "Organización",
    icon: Calendar,
    emojis: [
      "📅",
      "🗓️",
      "⏰",
      "📌",
      "📋",
      "✅",
      "📂",
      "🗃️",
      "🏷️",
      "🔖",
      "✉️",
      "📍",
    ],
  },
  {
    id: "entertainment",
    name: "Entretenimiento",
    icon: Gamepad2,
    emojis: [
      "🎮",
      "🎬",
      "🎵",
      "🎨",
      "🎭",
      "🎲",
      "🧩",
      "🎸",
      "📺",
      "🎧",
      "🎤",
      "🕹️",
    ],
  },
  {
    id: "other",
    name: "Otros",
    icon: MoreHorizontal,
    emojis: [
      "🔔",
      "⚠️",
      "❓",
      "❗",
      "✨",
      "🎉",
      "🌟",
      "🌈",
      "🌙",
      "☀️",
      "🌱",
      "♻️",
    ],
  },
];


/** Categories shown before the user taps "Ver más". */
export const EMOJI_PREVIEW_CATEGORY_COUNT = 3;

export const DEFAULT_LIST_COLOR = LIST_COLORS[0].value;
export const DEFAULT_LIST_ICON = EMOJI_CATEGORIES[0].emojis[0];

/** Flat, de-duplicated list of every emoji available. */
export const ALL_LIST_EMOJIS: string[] = Array.from(
  new Set(EMOJI_CATEGORIES.flatMap((c) => c.emojis)),
);
